# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noTABene_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.Transcription_tab = QtWidgets.QWidget()
        self.Transcription_tab.setObjectName("Transcription_tab")
        self.TranscriptionBox = QtWidgets.QTextBrowser(self.Transcription_tab)
        self.TranscriptionBox.setGeometry(QtCore.QRect(10, 10, 771, 531))
        self.TranscriptionBox.setObjectName("TranscriptionBox")
        self.Communication_status = QtWidgets.QLabel(self.Transcription_tab)
        self.Communication_status.setGeometry(QtCore.QRect(670, 540, 111, 21))
        self.Communication_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Communication_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Communication_status.setObjectName("Communication_status")
        self.tabWidget.addTab(self.Transcription_tab, "")
        self.Image_tab = QtWidgets.QWidget()
        self.Image_tab.setObjectName("Image_tab")
        self.graphicsView = QtWidgets.QGraphicsView(self.Image_tab)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 771, 541))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.Image_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Conectique du timer de la tab Série
        self.timer_du_timer = QTimer()
        self.timer_du_timer.timeout.connect(self.Print_Hello)
        self.timer_du_timer.start(1000)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NoTABene"))
        self.Communication_status.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Transcription_tab), _translate("MainWindow", "Transcription"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image_tab), _translate("MainWindow", "Image"))


    def Print_Hello(self):
        self.TranscriptionBox.setText("Hello")
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())